os_type: linux
shell_type: bash

provisioner:
  name: shell
  data_path: ./

platforms:

  - name: docker-alpine
    provisioner:
      root_path: "/tmp/kitchen"
      command: cd /tmp/kitchen/data; . integration/init.sh
    transport:
      name: rsync_ssh
    driver_config:
      name: docker
      image: alpine
      build_context: integration
      dockerfile: <%= ENV['PWD'] %>/integration/alpine.dockerfile
      privileged: true
      use_internal_docker_network: true
      run_command:
      volume:
        - <%= ENV['PWD'] %>:/home/kitchen/prog/my-plans
        - <%= ENV['HOME'] %>/.hab:/home/kitchen/.hab
        - hab_pkgs:/hab/pkgs
        - hab_studios:/hab/studios
        - /var/run/docker.sock:/var/run/docker.sock

suites:
  - name: default

